### ISSUE TITLE
IE compatibility

### ISSUE THREAD

**Issue by Nibu1997** [webmandesign/receptar#3]
For me the theme does not work in IE 11.

it looks like this:
![receptar- internet explorer-001](https://cloud.githubusercontent.com/assets/15012913/11297411/7ade0e54-8f78-11e5-9731-1f64da8b8f23.jpg)

**Comment by webmandesign** [comment]
Hi,

Please log a ticket at http://support.webmandesign.eu as I do not provide support via Github.

Regards,

Oliver
