### ISSUE TITLE
Customizable post thumbnail image size

### ISSUE THREAD

**Issue by danielkucera** [webmandesign/receptar#5]
Ahoj, could this size be made customizable?

https://github.com/webmandesign/receptar/blob/c54b1f96821aceaa6a2ca5bbd30514ec180f324f/template-parts/content.php#L23

**Comment by danielkucera** [comment]
Oh sorry, I just found the solution: https://support.webmandesign.eu/forums/topic/blurry-featured-images/
But it somehow doesn't work for me...

**Comment by danielkucera** [comment]
```If you already have some images on your wesbsite, these need to be rescaled when using the theme. Please use a plugin such as Force Regenerate Thumbnails to do this for you.```

**Comment by webmandesign** [comment]
Ahoj!

Please follow the instructions in the support forum ticket to set the correct post thumbnail image size recommended by the theme.

If you set the image size correctly in WordPress admin and you need to make your older, already uploaded images to adhere to the new size, you need to use the Force Regenerate Thumbnails plugin (or similar one). (This is actually also stated in the support ticket you've linked to.)

If you still have an issue, please describe it in more details at https://support.webmandesign.eu/ as GitHub is not a correct place to discuss the theme/WordPress setup issues ;)

Thanks for understanding!

Hezký den!

Oliver
